export { default as CameraOff } from "./camera-off.svg";
export { default as CameraOn } from "./camera-on.svg";
export { default as Coffee } from "./coffee.svg";
export { default as DeerFrame } from "./deer_frame.svg";
export { default as Exit } from "./exit.svg";
export { default as Google } from "./google.svg";
export { default as Heart } from "./heart.svg";
export { default as Marchmellow } from "./marchmellow.svg";
export { default as MicrophoneOff } from "./micro-off.svg";
export { default as MicrophoneOn } from "./micro-on.svg";
export { default as Monkey } from "./monkey.svg";
export { default as Moon } from "./moon.svg";
export { default as Mushroom } from "./mushroom.svg";
export { default as Rope } from "./rope.svg";
export { default as Sun } from "./sun.svg";
export {default as Logo } from "./logo.svg";
